Traceback (most recent call last):
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/psutil/_common.py", line 342, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/reporter.py", line 218, in <module>
    reporter.run()
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/reporter.py", line 176, in run
    self.perform_iteration()
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/reporter.py", line 165, in perform_iteration
    stats = self.get_all_stats()
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/reporter.py", line 156, in get_all_stats
    "workers": self.get_workers(),
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/reporter.py", line 131, in get_workers
    ]) for x in psutil.process_iter() if running_worker(x.name())
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/reporter.py", line 129, in <listcomp>
    x.as_dict(attrs=[
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/psutil/__init__.py", line 1570, in process_iter
    if proc.is_running():
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/psutil/__init__.py", line 694, in is_running
    return self == Process(self.pid)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/psutil/__init__.py", line 446, in __init__
    self._init(pid)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/psutil/__init__.py", line 473, in _init
    self.create_time()
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/psutil/__init__.py", line 823, in create_time
    self._create_time = self._proc.create_time()
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/psutil/_pslinux.py", line 1513, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/psutil/_pslinux.py", line 1723, in create_time
    ctime = float(self._parse_stat_file()['create_time'])
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/psutil/_pslinux.py", line 1513, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/psutil/_common.py", line 345, in wrapper
    return fun(self)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/psutil/_pslinux.py", line 1565, in _parse_stat_file
    name = data[data.find(b'(') + 1:rpar]
KeyboardInterrupt
