Ray worker pid: 27776
2019-08-13 11:15:14,445	WARNING worker.py:343 -- WARNING: Falling back to serializing objects of type <class 'torch.nn.backends.thnn.THNNFunctionBackend'> by using pickle. This may be inefficient.
2019-08-13 11:15:14,470	WARNING worker.py:343 -- WARNING: Falling back to serializing objects of type <class 'torch.Size'> by using pickle. This may be inefficient.
Exception in thread ray_import_thread:
Traceback (most recent call last):
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/redis/connection.py", line 185, in _read_from_socket
    raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
OSError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/import_thread.py", line 69, in _run
    msg = import_pubsub_client.get_message()
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/redis/client.py", line 3135, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/redis/client.py", line 3036, in parse_response
    return self._execute(connection, connection.read_response)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/redis/client.py", line 3013, in _execute
    return command(*args)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/redis/connection.py", line 637, in read_response
    response = self._parser.read_response()
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/redis/connection.py", line 290, in read_response
    response = self._buffer.readline()
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/redis/connection.py", line 224, in readline
    self._read_from_socket()
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/redis/connection.py", line 199, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)

Traceback (most recent call last):
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/workers/default_worker.py", line 98, in <module>
    ray.worker.global_worker.main_loop()
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/worker.py", line 1052, in main_loop
    self._wait_for_and_process_task(task)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/worker.py", line 1003, in _wait_for_and_process_task
    self._process_task(task, execution_info)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/worker.py", line 930, in _process_task
    self._store_outputs_in_object_store(return_object_ids, outputs)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/worker.py", line 841, in _store_outputs_in_object_store
    self.put_object(object_ids[i], outputs[i])
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/worker.py", line 384, in put_object
    self.store_and_register(object_id, value)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/worker.py", line 318, in store_and_register
    self.current_job_id))
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/utils.py", line 480, in _wrapper
    return orig_attr(*args, **kwargs)
  File "pyarrow/_plasma.pyx", line 498, in pyarrow._plasma.PlasmaClient.put
  File "pyarrow/_plasma.pyx", line 328, in pyarrow._plasma.PlasmaClient.create
  File "pyarrow/error.pxi", line 83, in pyarrow.lib.check_status
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/pyarrow_files/pyarrow/compat.py", line 115, in frombytes
    def frombytes(o):
KeyboardInterrupt
